/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  'User Guide': [{type: 'autogenerated', dirName: 'user-guide'}],
  'Icon Sets': [
    'iconsets/fluentui',
    'iconsets/materialdesign',
    'iconsets/fontawesome',
    {
      type: 'category',
      label: 'Large Sets',
      items: ['iconsets/simple', 'iconsets/gameicons', 'iconsets/remix'],
    },
    {
      type: 'category',
      label: 'Medium Sets',
      items: ['iconsets/bootstrap', 'iconsets/tabler', 'iconsets/teeny'],
    },
    {
      type: 'category',
      label: 'Small Sets',
      items: ['iconsets/feather', 'iconsets/octicons', 'iconsets/crypto', 'iconsets/box', 'iconsets/weather', 'iconsets/publicdomain', 'iconsets/hero', 'iconsets/pixelart'],
    },
    {
      type: 'category',
      label: 'Color Icons',
      items: ['iconsets/msicons', 'iconsets/vscode', 'iconsets/twemoji', 'iconsets/animated', 'iconsets/lacap', 'iconsets/flags'],
    },
    {
      type: 'category',
      label: 'Icon Fonts',
      items: ['iconsets/azdevmdl2', 'iconsets/segoemdl2', 'iconsets/icofont', 'iconsets/bowtie'],
    },
  ],

  'Getting Started': [{type: 'autogenerated', dirName: 'getting-started'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
